name: causal_impact
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.1.2
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - statsmodels=0.14.0
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - m2w64-toolchain  # Required for PyMC on Windows
  - pip:
    - causalimpact==0.2.6
    - pymc==5.7.2
    - arviz==0.14.0
    - pytensor==2.14.2
    - streamlit==1.25.0
    - plotly==5.16.1
    - altair==5.5.0
    - xarray==2024.7.0
    - xarray-einstats==0.8.0
    - h5py==3.14.0
    - netCDF4==1.7.2
    - patsy==1.0.1
    - cloudpickle==3.1.1
    - requests==2.32.4 